# Generated by Django 3.2.5 on 2023-09-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EPaperEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': '電子報訂閱信箱',
                'verbose_name_plural': '電子報訂閱信箱',
            },
        ),
    ]
