# Generated by Django 3.2.5 on 2023-09-22 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epaper', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='epaperemail',
            options={'verbose_name': 'epaper subscribe mail', 'verbose_name_plural': 'epaper subscribe mails'},
        ),
    ]
