# Generated by Django 3.2.5 on 2023-09-19 01:46

import core.helpers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_auto_20230917_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='語言代碼')),
                ('language', models.CharField(max_length=50, verbose_name='系統語言')),
                ('sitename', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='系統語言')),
                ('logo', models.FileField(blank=True, null=True, upload_to=core.helpers.upload_handle, verbose_name='logo圖片')),
                ('favicon', models.FileField(blank=True, null=True, upload_to=core.helpers.upload_handle, verbose_name='favicon圖片')),
                ('style', models.FileField(blank=True, null=True, upload_to=core.helpers.upload_handle, verbose_name='CSS style')),
                ('detail_template', models.CharField(choices=[('Template-1', '版型一'), ('Template-2', '版型二')], default='Template-1', max_length=100, verbose_name='詳細頁面版型')),
                ('facebook', models.CharField(blank=True, max_length=100, null=True, verbose_name='Facebook link')),
                ('instagram', models.CharField(blank=True, max_length=100, null=True, verbose_name='Instagram link')),
                ('twitter', models.CharField(blank=True, max_length=100, null=True, verbose_name='Twitter link')),
                ('home_type1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='home_type1_set', to='products.productcategory', verbose_name='左上商品分類')),
                ('home_type2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='home_type2_set', to='products.productcategory', verbose_name='左下商品分類')),
                ('home_type3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='home_type3_set', to='products.productcategory', verbose_name='右側商品分類')),
            ],
            options={
                'verbose_name': '網站設定',
                'verbose_name_plural': '網站設定',
            },
        ),
    ]
