# Generated by Django 3.2.5 on 2023-09-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='電話'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='sitename',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='系統名稱'),
        ),
    ]
