# Generated by Django 3.2.5 on 2023-09-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20230919_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='建立日期'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='修改日期'),
        ),
    ]
